### PR TITLE
Php8.2 deprecation fixes

### PR DESCRIPTION
**Pull request by ipundit**
My apologies; I should have done a search in the repository of 'static:: to find all instances of this deprecation error. There's one more in Model.last(). Found and fixed.

### CODE REVIEW

**Comment by shmax** [comment]
Can you please rebase or merge latest from master? I'm seeing some stuff in this PR that we already merged.

**Comment by ipundit** [comment]
It's only a one line change to review; shown in:
https://github.com/php-activerecord/activerecord/pull/26/commits/966d366eb62d3b374cfef5eecfc2f515fa1bee58

**Comment by shmax** [comment]
Yes, I get it, but this is sort of a janky PR. You need to get in the habit of fixing this kind of problem. Please give it a try and let me know if you have any trouble.

**Comment by ipundit** [comment]
Replaced with https://github.com/php-activerecord/activerecord/pull/28

**Comment by shmax** [comment]
Much appreciated, but for next time you can fix this sort of situation without creating a new branch. There's some [good information on github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) about this sort of thing, but in a nutshell you could have done something like this:

```sh
git fetch upstream
git rebase upstream/main
git push -f
```

**Pull request closed without merging**
