### PR TITLE
Update Model.php

### PR DESCRIPTION
**Pull request by EclipseMarketingUk**
removal of cound error

### CODE REVIEW

**Comment by shmax** [comment]
Hi, sorry for the long delay--I didn't notice that anyone was doing PRs. Can you explain what it is you were fixing, here?

**Comment by craig-stanfield** [comment]
Hi shmax, yes this was a notice from after php upgrade (I think 7.4). I know bad practice to use the @ but it tidied the logs.

**Comment by shmax** [comment]
Can you please paste the notice? I'm not seeing anything in my environment...

**Comment by shmax** [comment]
Thanks much

**Pull request merged**
